name: Run Linter
on:  
  push:
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./WebApp
        run: yarn
      - name: Run Lint
        working-directory: ./WebApp
        run: yarn lint