name: Run WebApp tests
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApp
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: yarn
      - name: Run tests
        run: yarn test
