name: Run Tests
on: [pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./WebApp
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        working-directory: ./WebApp
        run: yarn
      - name: Run tests
        working-directory: ./WebApp
        run: yarn test
